apiVersion: v1
kind: Pod
metadata:
  name: pizzeria-pod
  labels:
    app: pizzeria
spec:
  containers:
    - name: frontend
      imagePullPolicy: Never
      image: pizzeria
      env:
      - name: MONGODB_URI
        value: "mongodb://backend:27017/"
      - name: PORT
        value: "4200"
      - name: SECRET
        value: "secret"
